# Generated by Django 2.1.7 on 2019-03-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('autograph', models.CharField(default='这个人没有填简介啊~~~', max_length=255)),
                ('birth', models.DateField(null=True)),
                ('fans', models.IntegerField(default=0)),
                ('follow', models.IntegerField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('cols', models.IntegerField(default=0)),
                ('com', models.IntegerField(default=0)),
                ('icon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Icon')),
                ('sex', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Sex')),
                ('skin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Skin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='followers',
            name='concern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='concern', to='user.User'),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user.User'),
        ),
    ]
