# Generated by Django 2.1.7 on 2019-03-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('click', models.IntegerField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('cols', models.IntegerField(default=0)),
                ('com', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DairyCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('Dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dairy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DairyCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('Dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dairy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DairyFbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('Dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dairy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DairyImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50, null=True)),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dairy')),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('click', models.IntegerField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('cols', models.IntegerField(default=0)),
                ('com', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('Dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dynamic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('Dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dynamic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('Dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dynamic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50, null=True)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Dynamic')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('click', models.IntegerField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('cols', models.IntegerField(default=0)),
                ('com', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestFbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.Test')),
            ],
        ),
    ]
