# Generated by Django 2.1.7 on 2019-03-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='type',
            field=models.CharField(default='dairy', max_length=255),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='type',
            field=models.CharField(default='dynamic', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
